In [1]:
import pandas as pd
import numpy as np
import difflib
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

**Data collection and Pre-processing**

In [2]:
movies_data = pd.read_csv("movies.csv")
movies_data.head(2)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski


In [3]:
movies_data.shape

(4803, 24)

In [4]:
movies_data.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [5]:
movies_data.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

**Feature Selcetion**

In [6]:
relevant_features = ['genres' , 'keywords', 'tagline' , 'cast' , 'director' , 'overview', 'title']
print(relevant_features)

['genres', 'keywords', 'tagline', 'cast', 'director', 'overview', 'title']


In [7]:
# Fill null values in relevent features list with empty string.

for feature in relevant_features:
    movies_data[feature] = movies_data[feature].fillna('')

In [8]:
# combine all the selected features.

combined_features = movies_data['title']+ ' ' + movies_data['genres']+ ' ' + movies_data['overview']+ ' ' + movies_data['keywords']+ ' ' + movies_data['tagline']+ ' ' + movies_data['cast']+ ' ' + movies_data['director']

In [9]:
print(combined_features)

0       Avatar Action Adventure Fantasy Science Fictio...
1       Pirates of the Caribbean: At World's End Adven...
2       Spectre Action Adventure Crime A cryptic messa...
3       The Dark Knight Rises Action Crime Drama Thril...
4       John Carter Action Adventure Science Fiction J...
                              ...                        
4798    El Mariachi Action Crime Thriller El Mariachi ...
4799    Newlyweds Comedy Romance A newlywed couple's h...
4800    Signed, Sealed, Delivered Comedy Drama Romance...
4801    Shanghai Calling  When ambitious New York atto...
4802    My Date with Drew Documentary Ever since the s...
Length: 4803, dtype: object


**Convert Text data to numerical vector**

In [10]:
# using TfidVectorizer we can Converts text into vectors

vectorizer = TfidfVectorizer()

feature_vector = vectorizer.fit_transform(combined_features)

In [11]:
print(feature_vector)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 313949 stored elements and shape (4803, 31349)>
  Coords	Values
  (0, 2127)	0.1996044560566861
  (0, 575)	0.05874744494063195
  (0, 719)	0.06731130606660389
  (0, 9987)	0.08381139359719003
  (0, 24541)	0.0781825087247856
  (0, 10262)	0.07827254609275694
  (0, 13811)	0.035660637876271516
  (0, 27773)	0.08014292025946683
  (0, 241)	0.19409945746418178
  (0, 4899)	0.1227933750552499
  (0, 20589)	0.1896015461079148
  (0, 17433)	0.14044787266458833
  (0, 14375)	0.040962029716589216
  (0, 8023)	0.17699936996038537
  (0, 28074)	0.030408685842708415
  (0, 18689)	0.14159553128651622
  (0, 20521)	0.36500873710577947
  (0, 20010)	0.04792044316122149
  (0, 29297)	0.15249563870657573
  (0, 18451)	0.10739535627892342
  (0, 4241)	0.060925642227548336
  (0, 2764)	0.09643239478297781
  (0, 28189)	0.14279919495279256
  (0, 3061)	0.09808742782138465
  (0, 10623)	0.13632661307394978
  :	:
  (4802, 21900)	0.08589177004191777
  (4802, 9395)	0.074

**Cosine Similarity**

In [12]:
# Getting the similarity scores using cosine_similarity : Measures similarity between two vectors using the cosine of the angle between them.

similarity = cosine_similarity(feature_vector)

In [13]:
print(similarity)

[[1.         0.05399851 0.03084844 ... 0.02434614 0.02809646 0.00665587]
 [0.05399851 1.         0.04098103 ... 0.05353934 0.03667414 0.01552356]
 [0.03084844 0.04098103 1.         ... 0.02269726 0.0425641  0.01228775]
 ...
 [0.02434614 0.05353934 0.02269726 ... 1.         0.02986951 0.03920937]
 [0.02809646 0.03667414 0.0425641  ... 0.02986951 1.         0.02879619]
 [0.00665587 0.01552356 0.01228775 ... 0.03920937 0.02879619 1.        ]]


In [14]:
# This is the similarity score of each movie comparing with other movies

In [15]:
# we can check the shape also for this

print(similarity.shape)

(4803, 4803)


**Getting name of movie from user**

In [16]:
movie_name = input('Search For Movie = ')

Search For Movie =  Extraction


In [17]:
# Creating a list with all the movies name given in dataset

list_of_all_movies = movies_data['title'].tolist()
print(list_of_all_movies)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [18]:
# Finding the closest match of the movie entered by user

**Using difflib**

In [19]:
# use difflib.get_close_match and pass the parameters as movie entered by user and second as list of all movies

find_closest_match = difflib.get_close_matches(movie_name , list_of_all_movies)
print(find_closest_match)

['Extract', 'Vacation', 'Restoration']


In [20]:
# selecting only the first movie matched with the movie entered by user

top_match = find_closest_match[0]
print(top_match)

Extract


In [21]:
# Finding the index value of movie with title

index_of_movie = movies_data[movies_data.title == top_match]['index'].values[0]
print(index_of_movie)

3320


**Using similarity to find the similarity score**

In [22]:
# Getting the similarity score for the list of movies similar to the movie entered by user

similarity_score = list(enumerate(similarity[index_of_movie]))
print(similarity_score)

[(0, np.float64(0.023434391599286345)), (1, np.float64(0.05170470608027581)), (2, np.float64(0.030768086929350003)), (3, np.float64(0.03101492633475894)), (4, np.float64(0.024419374097779493)), (5, np.float64(0.03350374792355658)), (6, np.float64(0.032413163850969914)), (7, np.float64(0.04958079914792207)), (8, np.float64(0.01346263061894294)), (9, np.float64(0.04704161128014734)), (10, np.float64(0.04811922291528374)), (11, np.float64(0.03374595442135428)), (12, np.float64(0.03173532299558113)), (13, np.float64(0.036899974878646526)), (14, np.float64(0.08290627171474722)), (15, np.float64(0.04103473528407276)), (16, np.float64(0.020552255288084333)), (17, np.float64(0.087630625223907)), (18, np.float64(0.054956447605594996)), (19, np.float64(0.034054904389795235)), (20, np.float64(0.06426834543660516)), (21, np.float64(0.022616263145540952)), (22, np.float64(0.03426348103340644)), (23, np.float64(0.03330788735684551)), (24, np.float64(0.048804736480904824)), (25, np.float64(0.03012409

**Sorting the movie based on similarity score (descending order)**

In [23]:
sorted_similar_movies = sorted(similarity_score , key = lambda x:x[1] , reverse = True)
print(sorted_similar_movies)

[(3320, np.float64(1.0000000000000002)), (1485, np.float64(0.22856010107993463)), (3042, np.float64(0.147015405837483)), (2597, np.float64(0.12354559151243139)), (3725, np.float64(0.12142102041719434)), (1920, np.float64(0.1207427930224219)), (314, np.float64(0.11788007500781103)), (1416, np.float64(0.11366885974846974)), (1364, np.float64(0.10948135950695878)), (1508, np.float64(0.10724100328490861)), (4074, np.float64(0.10680402306211091)), (3375, np.float64(0.10624461999416618)), (3379, np.float64(0.10621883364328111)), (37, np.float64(0.10609791323053501)), (3362, np.float64(0.10565975843827184)), (903, np.float64(0.10361021156313989)), (2454, np.float64(0.1021997655678808)), (1397, np.float64(0.10094716214494673)), (4589, np.float64(0.09816714946548091)), (3210, np.float64(0.09756352833031537)), (1283, np.float64(0.09748468319871328)), (1616, np.float64(0.09718652322326894)), (2687, np.float64(0.09701170385805381)), (1328, np.float64(0.09667009630906405)), (2539, np.float64(0.0964

In [24]:
# Print the name of suggested or similar movies based on the index value 
# we will create a for loop to print the first 10 recommended movies 

In [25]:
print('Recommended Movies for you : \n')

i = 1
for movie in sorted_similar_movies:
    index = movie[0]
    title_from_index = movies_data[movies_data.index == index]['title'].values[0]

    if i<11:
        print(i,'.', title_from_index)
        i+=1

Recommended Movies for you : 

1 . Extract
2 . The Watcher
3 . The Gift
4 . Confidence
5 . The Sweeney
6 . Warrior
7 . The Spanish Prisoner
8 . Jersey Girl
9 . Horrible Bosses
10 . The Number 23


# Movie Recommendation System

In [27]:
movie_name = input('Search For Movie = ')

find_closest_match = difflib.get_close_matches(movie_name, list_of_all_movies, n=3, cutoff=0.5)

if find_closest_match:   # Clean check first
    try:
        top_match = find_closest_match[0]
        index_of_movie = movies_data[movies_data.title == top_match]['index'].values[0]

        similarity_score = list(enumerate(similarity[index_of_movie]))
        sorted_similar_movies = sorted(similarity_score, key=lambda x: x[1], reverse=True)

        print("Recommended movies for you : \n")
        i = 1
        for movie in sorted_similar_movies:
            index = movie[0]
            title_from_index = movies_data[movies_data.index == index]['title'].values[0]

            if i < 16:
                print(i, '.', title_from_index)
                i += 1

    except Exception as e:   # catches any unexpected errors
        print("An error occurred while generating recommendations:", e)

else:
    print("Movie not found in dataset.")
    print("Did you mean one of these?")
    print(find_closest_match if find_closest_match else "No close matches found.")


Search For Movie =  Extracrtion


Recommended movies for you : 

1 . Extract
2 . The Watcher
3 . The Gift
4 . Confidence
5 . The Sweeney
6 . Warrior
7 . The Spanish Prisoner
8 . Jersey Girl
9 . Horrible Bosses
10 . The Number 23
11 . It Follows
12 . Redbelt
13 . Factory Girl
14 . Oz: The Great and Powerful
15 . A Serious Man


Recommended movies for you : 

1 . Deadpool
2 . X-Men
3 . The Incredible Hulk
4 . Iron Man 2
5 . Spider-Man 2
6 . X-Men Origins: Wolverine
7 . X-Men: Apocalypse
8 . The Amazing Spider-Man
9 . X-Men: Days of Future Past
10 . Men of War
11 . Ant-Man
12 . Man of Steel
13 . The Avengers
14 . Thor: The Dark World
15 . The Shadow


In [28]:
# Saving processed data to deploy on streamlit

In [29]:
import pickle


In [30]:
pickle.dump(movies_data, open('movies.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl' , 'wb'))